### PR TITLE
Added basic text definitions

### PR DESCRIPTION
**Pull request by am2021**
Still needs to add images

### CODE REVIEW

**Review by wintleh — COMMENTED** [review]
Looks good, but do you have a citation for the info?

**Comment by am2021** [comment]
> Looks good, but do you have a citation for the info?

I added the link to our doc. Where are we putting citations on the site?

**Comment by wintleh** [comment]
> 
> 
> > Looks good, but do you have a citation for the info?
> 
> I added the link to our doc. Where are we putting citations on the site?

I just added a citation section to the bottom of the page.

**Review by roched1atwit — APPROVED** [review]
Thumbs up

**Pull request merged**
